# -*- coding: utf-8 -*-
"""Vervolg: teksten van de subpagina's en de omzetting zelf."""

DIENST = [
    ("Draagmuur doorbreken: zo werkt het, wat het kost en wie het regelt | De Draagmuurkoning",
     "Removing a load-bearing wall in the Netherlands: how it works | De Draagmuurkoning"),
    ("Een draagmuur doorbreken kan bijna altijd: er komt een stalen ligger voor in de plaats. Berekening, vergunning, uitvoering en afwerking door één team.",
     "A load-bearing wall can nearly always be opened up: a steel beam takes over the load. Calculation, permit, execution and finishing by one team."),
    ("Draagmuur doorbreken: zo werkt het | De Draagmuurkoning", "How removing a load-bearing wall works | De Draagmuurkoning"),
    ("Een draagmuur doorbreken kan bijna altijd. Berekening, vergunning, uitvoering en afwerking door één team.",
     "A load-bearing wall can nearly always be opened up. Calculation, permit, execution and finishing by one team."),
    (">De dienst<", ">The service<"),
    ("<h1>Draagmuur doorbreken</h1>", "<h1>Removing a load-bearing wall</h1>"),
    ("Een draagmuur doorbreken kan bijna altijd. Er komt een stalen ligger voor in de plaats die het gewicht van de verdiepingen overneemt. Daarvoor zijn een constructieberekening en meestal een omgevingsvergunning nodig. Wij regelen dat hele traject; de uitvoering zelf duurt meestal twee tot vijf werkdagen.",
     "A load-bearing wall can nearly always be opened up. A steel beam takes its place and carries the floors above. That needs a structural calculation and, in almost all cases, an environmental permit from your municipality. We arrange the whole thing in English; the work itself usually takes two to five working days."),
    ("Hoe weet je of een muur dragend is?", "How do you know if a wall is load-bearing?"),
    ("Een dragende muur houdt meer omhoog dan zichzelf: de vloerbalken van de verdieping erboven, een muur op de verdieping, soms het dak. Vuistregels zijn er wel (steenachtige muren van 100 mm en dikker zijn vaak dragend, de richting van de vloerbalken verklapt veel), maar zekerheid geeft alleen de tekening of een blik van een constructeur.",
     "A load-bearing wall holds up more than itself: the joists of the floor above, a wall on the storey above, sometimes the roof. There are rules of thumb (masonry walls of 100 mm and thicker often carry load, and the direction of the joists tells you a lot), but only the drawings or an engineer can give you certainty."),
    ("Praktisch: stuur ons een paar foto's van de muur, de ruimte erboven en, als je die hebt, de plattegrond. Wij zien dan snel of de muur dragend is en wat erbij komt kijken. Dat kost je niets.",
     "In practice: send us a few photos of the wall, the room above it and, if you have them, the floor plans. We can usually tell you quickly whether the wall carries load and what the job involves. That costs you nothing."),
    ("Wat er voor je muur in de plaats komt", "What replaces your wall"),
    ("Het gewicht dat de muur droeg moet ergens heen. Meestal is dat een stalen ligger die aan beide kanten oplegt op het muurwerk dat blijft staan. Bij bredere openingen of als er weinig muur overblijft, komen er stalen kolommen onder de ligger te staan: een portaal. De berekening wijst uit welk profiel nodig is, hoe groot de opleggingen moeten zijn en of de fundering het aankan.",
     "The load the wall carried has to go somewhere. Usually that is a steel beam bearing on the masonry that stays on both sides. For wider openings, or where little wall is left, steel columns go under the beam: a portal frame. The calculation shows which section is needed, how large the bearings must be and whether the foundation can take it."),
    ("Dat rekenwerk doet onze eigen constructeur, volgens de Eurocode, in een rapport dat de gemeente rechtstreeks kan toetsen. Geen extern bureau, geen wachttijd tussen aannemer en rekenaar: wie rekent en wie uitvoert zitten hier aan dezelfde tafel.",
     "Our own structural engineer does that work to the Eurocode, in a report the municipality can assess directly. No external consultant, no waiting between builder and engineer: the person who calculates and the person who builds sit at the same table."),
    ("Zo verloopt de klus", "How the job runs"),
    ("Na akkoord op de offerte tekenen we de bestaande en nieuwe situatie en rekenen we de doorbraak door. Zodra de vergunning rond is, plannen we de uitvoering. Die verloopt altijd in dezelfde volgorde: stutten zetten die het gewicht tijdelijk overnemen, de muur zagen (met stofafzuiging; het blijft sloopwerk, maar geen bouwput), het staal stellen en afvullen, de stutten eruit en het herstelwerk: aanhelen, stuken of verven. Je ziet aan het eind niet meer dat er een muur stond.",
     "Once you approve the quote we draw the existing and the new situation and calculate the opening. As soon as the permit is granted we schedule the work. It always runs in the same order: propping to carry the load temporarily, sawing the wall (with dust extraction; it stays demolition work, but it is not a building site), setting and packing the steel, taking out the props, and making good: patching, plastering or painting. At the end you cannot tell a wall stood there."),
    ("De meeste doorbraken zijn in twee tot vijf werkdagen klaar. Tijdens de klus kun je gewoon thuis blijven wonen.",
     "Most jobs are finished in two to five working days. You can stay in the house while we work."),
    ("Vergunning en veiligheid", "Permit and safety"),
    ("Voor het doorbreken van een dragende muur is vrijwel altijd een omgevingsvergunning nodig. De gemeente wil een tekening en een constructieberekening zien en heeft wettelijk acht weken om te beslissen. Wij dienen de aanvraag voor je in en beantwoorden de vragen die de gemeente stelt. Ook als je muur al doorgebroken is en de gemeente om papieren vraagt (legalisatie), kunnen we dat verzorgen.",
     "Removing a load-bearing wall almost always requires an environmental permit (omgevingsvergunning). The municipality wants to see a drawing and a structural calculation, and has eight weeks by law to decide. We submit the application for you and answer the questions they ask, all in Dutch on your behalf. If your wall has already been opened up and the municipality asks for paperwork afterwards, we can arrange that too."),
    ("Wat kost het?", "What does it cost?"),
    ("Dat hangt af van de overspanning, van wat er op de muur draagt en van hoever je de afwerking wilt laten gaan. Reken op enkele duizenden euro's voor het complete traject.",
     "That depends on the span, on what the wall carries and on how far you want the finishing to go. Expect a few thousand euros for the complete job."),
    ("De prijs komt in twee stappen tot stand. Na je foto's krijg je een richtprijs voor het geheel, met daarin een vaste prijs voor de tekening en de berekening. Zodra die berekening klaar is, is bekend welk profiel eronder moet, hoe de opleggingen eruitzien en wat er aan herstel nodig is. Op dat moment staat de prijs voor de uitvoering vast. Zo betaal je niet voor onzekerheid die we vooraf zouden moeten inschatten, en kom je achteraf niet voor verrassingen te staan.",
     "The price comes in two steps. After your photos you get an indicative price for the whole job, including a fixed price for the drawing and the calculation. Once that calculation is finished we know which section is needed, what the bearings look like and how much making good is involved. At that point the price for the work is fixed. That way you do not pay for uncertainty we would otherwise have to guess at, and there are no surprises afterwards."),
    ("Bij <a href=\"../projecten/\">onze projecten</a> zie je hoe zulke doorbraken er in de praktijk uitzien.",
     "Our <a href=\"/en/projects/\">projects</a> show what jobs like this look like in practice."),
    ("Weten of jouw muur eruit kan?", "Wondering whether your wall can go?"),
    ("Stuur een paar foto's en je hoort binnen één werkdag waar je aan toe bent.",
     "Send a few photos and you will know where you stand within one working day."),
]

PROJECTEN = [
    ("Projecten: uitgevoerde draagmuurdoorbraken | De Draagmuurkoning", "Projects: load-bearing walls we removed | De Draagmuurkoning"),
    ("Uitgevoerde draagmuurdoorbraken stap voor stap in beeld: aftekenen, stempelen, zagen, staal stellen en afwerken. Zoek de situatie die op de jouwe lijkt.",
     "Completed load-bearing wall removals, step by step: marking out, propping, sawing, setting the steel and finishing. Find the situation closest to yours."),
    ("Doorbraken stap voor stap in beeld, van de eerste lijn op de muur tot de afgewerkte doorgang.",
     "Jobs step by step, from the first line on the wall to the finished opening."),
    ("Doorbraken die we deden", "Walls we opened up"),
    ("Per project zie je hoe de klus verliep, van de eerste lijn op de muur tot de afgewerkte doorgang. Zoek de situatie die op de jouwe lijkt.",
     "Each project shows how the job ran, from the first line on the wall to the finished opening. Find the situation closest to yours."),
    ("Jouw muur als volgend project?", "Your wall next?"),
    ("Stuur een paar foto's en je hoort binnen één werkdag waar je aan toe bent.",
     "Send a few photos and you will know where you stand within one working day."),
]

OVER = [
    ("Wie wij zijn: aannemer en constructeur onder één naam | De Draagmuurkoning",
     "About us: contractor and structural engineer under one name | De Draagmuurkoning"),
    ("De Draagmuurkoning is de doorbraakservice van MAREE Aanneming en Cox Constructieadvies. Jordy Maree voert uit, Ir. Simon Cox rekent. Eén team, één aanspreekpunt.",
     "De Draagmuurkoning is the wall-removal service of MAREE Aanneming and Cox Constructieadvies. Jordy Maree builds, Ir. Simon Cox calculates. One team, one point of contact."),
    ("Wie wij zijn | De Draagmuurkoning", "About us | De Draagmuurkoning"),
    ("Aannemer en constructeur onder één naam: Jordy Maree voert uit, Ir. Simon Cox rekent.",
     "Contractor and structural engineer under one name: Jordy Maree builds, Ir. Simon Cox calculates."),
    ("Aannemer en constructeur, onder één naam", "Contractor and engineer, under one name"),
    ("Een doorbraak valt normaal uiteen in losse stukjes: een constructeur voor de berekening, een aannemer voor het zagen, een stukadoor voor de wand, en jij als verkeersregelaar ertussen. Wij hebben dat omgedraaid. Bij De Draagmuurkoning zitten de rekenaar en de uitvoerder aan dezelfde tafel, en jij hebt één aanspreekpunt.",
     "Normally a job like this falls apart into pieces: an engineer for the calculation, a builder for the sawing, a plasterer for the wall, and you directing traffic in between. In a language you may not speak. We turned that around. At De Draagmuurkoning the engineer and the builder sit at the same table, and you have one point of contact."),
    ("Waarom dit werkt", "Why this works"),
    ("Als de rekenaar en de uitvoerder elkaar niet kennen, gaat er tijd verloren in het doorgeven: de aannemer wacht op de berekening, de constructeur kent de bouwplaats niet, en bij elke vraag van de gemeente moet iedereen opnieuw aan tafel. Wij overleggen voordat er ook maar iets geoffreerd wordt. Daardoor sluit de offerte aan op wat er straks werkelijk gebeurt, en klopt het staal dat erin gaat.",
     "When the engineer and the builder do not know each other, time is lost in the handover: the builder waits for the calculation, the engineer has never seen the site, and every question from the municipality puts everyone back around the table. We talk before anything is quoted. That is why the quote matches what actually happens, and why the steel that goes in is the right steel."),
    ("We doen dit werk onder twee bedrijven die je los van elkaar ook gewoon kunt vinden: <a href=\"https://www.aannemingmaree.nl\">MAREE Aanneming</a> voor breder verbouwwerk en <a href=\"https://www.coxadvies.nl\">Cox Constructieadvies</a> voor constructieberekeningen. De Draagmuurkoning is de plek waar die twee samenkomen voor één klus: de doorbraak.",
     "We do this work through two companies you can also find separately: <a href=\"https://www.aannemingmaree.nl\">MAREE Aanneming</a> for wider building work and <a href=\"https://www.coxadvies.nl\">Cox Constructieadvies</a> for structural calculations. De Draagmuurkoning is where those two come together for one job: opening up a wall."),
    ("Zakelijk", "Company details"),
    ("MAREE Aanneming B.V. is ingeschreven bij de Kamer van Koophandel onder nummer 74031937, Cox Constructieadvies onder nummer 86134191. Voor het totaalpakket is MAREE Aanneming de contractpartij en hoofdaannemer; Cox Constructieadvies levert het teken- en rekenwerk.",
     "MAREE Aanneming B.V. is registered with the Dutch Chamber of Commerce under number 74031937, Cox Constructieadvies under number 86134191. For the complete package MAREE Aanneming is your contracting party and main contractor; Cox Constructieadvies provides the drawings and the structural design."),
    ("Jordy Maree aan het werk met de zaagmachine", "Jordy Maree at work with the saw"),
    ("Ir. Simon Cox, constructeur", "Ir. Simon Cox, structural engineer"),
    ("Uitvoering · MAREE Aanneming", "Execution · MAREE Aanneming"),
    ("Constructie · Cox Constructieadvies", "Structural engineering · Cox Constructieadvies"),
    ("Aannemer en specialist in betonzagen en boren, sinds 2019 met eigen bedrijf in de Betuwe. Jordy en zijn mensen stutten, zagen, stellen het staal en bouwen af tot en met het stucwerk. Wat hij belooft over de planning, maakt hij waar op de bouwplaats.",
     "Contractor and specialist in concrete sawing and drilling, running his own company in the Betuwe since 2019. Jordy and his people prop, saw, set the steel and finish up to and including the plastering. What he promises about the schedule, he delivers on site."),
    ("Constructeur, afgestudeerd aan de TU Eindhoven. Simon rekent elke doorbraak door volgens de Eurocode en zet zijn handtekening onder de berekening die naar de gemeente gaat. Dezelfde berekening waar de uitvoering letterlijk op bouwt.",
     "Structural engineer, graduated from Eindhoven University of Technology. Simon calculates every opening to the Eurocode and signs the report that goes to the municipality. The same report the work is literally built on."),
    ("Kennismaken?", "Like to meet?"),
    ("Stuur je vraag of een paar foto's van je muur. Je hoort binnen één werkdag van ons.",
     "Send your question or a few photos of your wall. You will hear from us within one working day."),
]

BEDANKT = [
    ("Aanvraag ontvangen | De Draagmuurkoning", "Request received | De Draagmuurkoning"),
    ("Je aanvraag is binnen. Je hoort binnen één werkdag van ons.", "Your request has arrived. You will hear from us within one working day."),
    (">Gelukt<", ">Thank you<"),
    ("Je aanvraag is binnen", "Your request has arrived"),
    ("Bedankt. We kijken naar je bericht en je foto's en je hoort binnen één werkdag van ons: met een concreet voorstel, of met de vragen die we nog hebben. Kijk intussen gerust bij <a href=\"../projecten/\" style=\"color:var(--gold)\">onze projecten</a> voor een situatie die op de jouwe lijkt.",
     "Thank you. We will look at your message and your photos, and you will hear from us within one working day: with a concrete proposal, or with the questions we still have. In the meantime, have a look at <a href=\"/en/projects/\" style=\"color:var(--gold)\">our projects</a> for a situation like yours."),
    ("Terug naar de homepage", "Back to the home page"),
]

PRIVACY = [
    ("Privacyverklaring | De Draagmuurkoning", "Privacy statement | De Draagmuurkoning"),
    ("Hoe De Draagmuurkoning omgaat met je gegevens: alleen wat nodig is om je aanvraag te beantwoorden, geen tracking, geen verkoop aan derden.",
     "How De Draagmuurkoning handles your data: only what is needed to answer your request, no selling to third parties."),
    (">Privacy<", ">Privacy<"),
    ("Privacyverklaring", "Privacy statement"),
    ("We gebruiken je gegevens voor precies één ding: reageren op je aanvraag. Geen nieuwsbrieven waar je niet om vroeg, geen verkoop aan derden. Voor de bezoekcijfers gebruiken we een teller zonder cookies; alles wat verder gaat, gebeurt alleen met jouw toestemming.",
     "We use your details for exactly one thing: answering your request. No newsletters you did not ask for, no selling to third parties. For visitor numbers we use a counter that sets no cookies; anything beyond that only happens with your consent."),
    ("Bezoekcijfers", "Visitor numbers"),
    ("We tellen met GoatCounter hoeveel mensen de site bezoeken en welke pagina's gelezen worden. Die teller zet geen cookies, volgt je niet over websites heen en slaat geen gegevens op waarmee je te herleiden bent. Daarom vragen we daar geen toestemming voor.",
     "We use GoatCounter to count how many people visit the site and which pages are read. That counter sets no cookies, does not follow you across websites and stores nothing that identifies you. That is why we do not ask consent for it."),
    ("Welke gegevens we verwerken", "What we process"),
    ("Vul je het contactformulier in, dan ontvangen we de gegevens die je zelf opgeeft: je naam, woonplaats, e-mailadres, eventueel je telefoonnummer, je bericht en de foto's die je meestuurt. Het formulier wordt technisch verzonden via Web3Forms, dat de inhoud aan ons doorlevert per e-mail.",
     "If you fill in the contact form, we receive the details you enter yourself: your name, town, email address, your phone number if you give it, your message and any photos you attach. The form is sent through Web3Forms, which passes the content on to us by email."),
    ("Waarvoor en hoe lang", "Why and for how long"),
    ("We gebruiken deze gegevens om je vraag te beantwoorden en, als het tot een opdracht komt, voor de offerte en de uitvoering. Aanvragen die niet tot een opdracht leiden, bewaren we niet langer dan nodig is voor het contact. Wordt het een project, dan bewaren we het dossier zolang de wettelijke bewaartermijnen dat vragen.",
     "We use these details to answer your question and, if it becomes a job, for the quote and the work itself. Requests that do not lead to a job are not kept longer than the contact requires. If it becomes a project, we keep the file for as long as Dutch law requires."),
    (">Cookies<", ">Cookies<"),
    ("Bij je eerste bezoek vragen we of we cookies mogen plaatsen. Zeg je nee, dan blijft het bij de cookie die je keuze onthoudt en de gegevens die nodig zijn om de site te tonen. Zeg je ja, dan gebruiken we Google Analytics om te zien welke pagina's gelezen worden en Google Ads om te meten welke advertentie tot een aanvraag leidt. We meten pas ná je toestemming, en je kunt je keuze op elk moment wijzigen via de link onderaan deze pagina.",
     "On your first visit we ask whether we may place cookies. If you say no, all that remains is the cookie that remembers your choice and the data needed to show the site. If you say yes, we use Google Analytics to see which pages are read and Google Ads to measure which advert leads to a request. We only measure after your consent, and you can change your choice at any time using the link below."),
    ("Hieronder staat welke cookies er precies zijn; die lijst wordt automatisch bijgehouden.",
     "The list below shows exactly which cookies there are; it is kept up to date automatically."),
    ("Mijn cookiekeuze wijzigen", "Change my cookie choice"),
    ("Je rechten", "Your rights"),
    ("Je mag altijd opvragen welke gegevens we van je hebben, ze laten corrigeren of laten verwijderen. Mail daarvoor naar simon.cox@coxadvies.nl. Ben je het niet eens met hoe we met je gegevens omgaan, dan kun je een klacht indienen bij de Autoriteit Persoonsgegevens.",
     "You can always ask which details we hold about you, have them corrected or have them deleted. Email simon.cox@coxadvies.nl. If you disagree with how we handle your data, you can complain to the Dutch Data Protection Authority (Autoriteit Persoonsgegevens)."),
    ("Verantwoordelijken", "Who is responsible"),
    ("Deze site is een samenwerking van MAREE Aanneming B.V. (KvK 74031937) en Cox Constructieadvies (KvK 86134191). Vragen over je gegevens kun je stellen via simon.cox@coxadvies.nl.",
     "This site is a collaboration between MAREE Aanneming B.V. (CoC 74031937) and Cox Constructieadvies (CoC 86134191). Questions about your data can go to simon.cox@coxadvies.nl."),
]
