# -*- coding: utf-8 -*-
"""Maakt de Engelse versie van draagmuurkoning.nl onder /en/.

De HTML-structuur blijft identiek; alleen teksten, links en taalattributen
veranderen. Zo blijven carrousel, formulier en cookiebanner werken zoals ze zijn.
"""
import re
from pathlib import Path

SITE = Path(r"C:\Users\simon\OneDrive\Cox Constructieadvies\website\draagmuurkoning.nl")

ROUTES = {
    "": "en",
    "draagmuur-doorbreken": "en/load-bearing-wall-removal",
    "projecten": "en/projects",
    "over-ons": "en/about",
    "faq": "en/faq",
    "privacy": "en/privacy",
    "bedankt": "en/thank-you",
}

WA_NL = "Hoi%2C%20ik%20wil%20graag%20een%20muur%20laten%20doorbreken.%20Hierbij%20een%20foto%20van%20de%20muur%3A"
WA_EN = "Hi%2C%20I%20would%20like%20to%20have%20a%20wall%20removed.%20Here%20is%20a%20photo%20of%20the%20wall%3A"

GEDEELD = [
    (">Draagmuur doorbreken<", ">Load-bearing walls<"),
    (">Projecten<", ">Projects<"),
    (">Wie wij zijn<", ">About us<"),
    (">Vragen<", ">FAQ<"),
    (">Offerte aanvragen<", ">Request a quote<"),
    (">Neem contact op<", ">Get in touch<"),
    ("Draagmuren doorbreken van berekening tot strakke wand. Eén team voor tekenwerk, constructie, vergunning, uitvoering en afwerking.",
     "Load-bearing wall removal, from the calculation to the finished wall. One team for drawings, structural design, permit, execution and finishing."),
    (">Pagina's<", ">Pages<"),
    (">Veelgestelde vragen<", ">Frequently asked questions<"),
    ("Eén team, twee bedrijven", "One team, two companies"),
    ("Uitvoering en afwerking · KvK 74031937", "Execution and finishing · CoC 74031937"),
    ("Berekening en tekenwerk · KvK 86134191", "Structural design and drawings · CoC 86134191"),
    ('aria-label="Paginaoverzicht"', 'aria-label="Site pages"'),
    ("App een foto van je muur", "WhatsApp a photo of your wall"),
    ("Stuur een appje: 06 1590 2335", "Send a WhatsApp: +31 6 1590 2335"),
    ('aria-label="Sluiten"', 'aria-label="Close"'),
    ('aria-label="Vorige foto"', 'aria-label="Previous photo"'),
    ('aria-label="Volgende foto"', 'aria-label="Next photo"'),
    (WA_NL, WA_EN),
]

CARROUSEL = [
    ("Bekijk de klus · 9 foto's", "See the job · 9 photos"),
    ("Bekijk alle foto's van de doorbraak in Bemmel", "See all photos of the job in Bemmel"),
    ("Bekijk alle foto's van de doorbraak in het appartement", "See all photos of the job in the apartment"),
    ("Foto's van de doorbraak in Bemmel", "Photos of the job in Bemmel"),
    ("Foto's van de doorbraak in het appartement", "Photos of the job in the apartment"),
    ("Bemmel · woonkeuken in een rijtjeshuis", "Bemmel · open kitchen in a terraced house"),
    ("2,52 m vrije opening · IPE 240 · opleggingen 350 mm", "2.52 m clear opening · IPE 240 · 350 mm bearings"),
    ("De wand tussen keuken en woonkamer ging eruit; naast de opening bleef een smal penant staan dat de nieuwe ligger draagt. Berekend, gestut, gezaagd en geplaatst door dit team.",
     "The wall between the kitchen and the living room came out. Next to the opening a narrow pier stayed, carrying the new beam. Calculated, propped, sawn and installed by this team."),
    ("Appartement · dragende betonwand eruit", "Apartment · load-bearing concrete wall removed"),
    ("Een dragende betonwand tussen woonkamer en keuken, over vrijwel de volle kamerbreedte. Het zaagpatroon werd op de wand afgetekend, de wand ging er blok voor blok uit en de blokken gingen per ladderlift rechtstreeks de container in.",
     "A load-bearing concrete wall between the living room and the kitchen, across almost the full width of the room. The cutting pattern was marked on the wall, the wall came out block by block, and the blocks went straight into the skip on a ladder lift."),
    ("De woonkamer voor de verbouwing. De wand naar de keuken gaat eruit.",
     "The living room before the work. The wall to the kitchen is coming out."),
    ("Op de muur staat wat eruit gaat; de portaalstempeling staat al.",
     "The wall is marked with what goes; the propping frame is already up."),
    ("Aan de keukenzijde hetzelfde verhaal: wat weggaat en wat blijft, precies volgens de berekening.",
     "Same story on the kitchen side: what goes and what stays, exactly as calculated."),
    ("De wand is eruit; stempels aan beide zijden dragen de verdieping.",
     "The wall is out; props on both sides carry the floor above."),
    ("Doorkijk over de nieuwe opening; de kruisjes markeren waar de ligger komt te rusten.",
     "Looking through the new opening; the crosses mark where the beam will bear."),
    ("De stalen ligger zit erin: een IPE 240 over een vrije opening van 2,52 meter.",
     "The steel beam is in: an IPE 240 over a clear opening of 2.52 metres."),
    ("De stutten kunnen eruit: van keuken tot woonkamer één ruimte.",
     "The props can come out: kitchen and living room are one space now."),
    ("Het staal is ingepakt en gestuukt; je ziet niet meer dat hier een muur stond.",
     "The steel is boxed in and plastered; you would never know a wall stood here."),
    ("De doorgang strak afgewerkt, klaar voor vloer en verf.",
     "The opening neatly finished, ready for flooring and paint."),
    ("Het zaagpatroon staat afgetekend op de wand, met het staalprofiel erbij.",
     "The cutting pattern is marked on the wall, with the steel section noted."),
    ("De portaalstempeling neemt het gewicht van de wand over.",
     "The propping frame takes the load off the wall."),
    ("Zagen van boven naar beneden; de bovenste blokken zijn eruit.",
     "Sawing from the top down; the upper blocks are out."),
    ("Elk blok is te tillen; zo verlaat de wand de woonkamer.",
     "Every block can be lifted; that is how the wall leaves the living room."),
    ("Door het raam, de ladderlift af, zo de container in.",
     "Out the window, down the ladder lift, straight into the skip."),
    ("Dezelfde wand vanaf de andere kant: gestempeld, en de ligger ligt al klaar op de vloer.",
     "The same wall from the other side: propped, with the beam already waiting on the floor."),
    ("De stalen ligger zit erin, in de grondverf, gezien vanaf de keukenzijde.",
     "The steel beam is in, in primer, seen from the kitchen side."),
    ("Terug in de woonkamer: de opening over de volle breedte, met het staal erin.",
     "Back in the living room: the opening across its full width, with the steel in place."),
    ("Afgetimmerd rond het staal; klaar voor stuc- en schilderwerk.",
     "Boxed in around the steel; ready for plastering and painting."),
    ("Stalen ligger IPE 240 geplaatst boven de doorbraak naar de keuken in Bemmel",
     "Steel beam IPE 240 installed above the opening to the kitchen in Bemmel"),
    ("Stalen ligger over brede doorbraak in dragende betonwand bij erker",
     "Steel beam over a wide opening in a load-bearing concrete wall by the bay window"),
    ("Woonkamer voor de verbouwing met de dichte wand naar de keuken", "Living room before the work, with the solid wall to the kitchen"),
    ("Gemarkeerde wand met portaalstempeling", "Marked-up wall with propping frame"),
    ("Markering op de keukenwand: wat weggaat en wat blijft", "Marks on the kitchen wall: what goes and what stays"),
    ("Open sparing met stempels aan beide zijden", "Open span with props on both sides"),
    ("Doorkijk over de nieuwe opening met afgetekende opleggingen", "View through the new opening with the bearings marked"),
    ("Geplaatste stalen ligger IPE 240 boven de opening", "Steel beam IPE 240 installed above the opening"),
    ("Overzicht van de woonkamer met de geplaatste ligger", "View of the living room with the beam in place"),
    ("Afgewerkte doorgang, het staal is ingepakt en gestuukt", "Finished opening, the steel boxed in and plastered"),
    ("Rechte opname van de afgewerkte doorgang tussen woonkamer en keuken", "Straight-on view of the finished opening between living room and kitchen"),
    ("Zaagpatroon afgetekend op de dragende betonwand", "Cutting pattern marked on the load-bearing concrete wall"),
    ("Portaalstempeling voor de afgetekende wand", "Propping frame in front of the marked-up wall"),
    ("Half weggezaagde wand met blokken onderin", "Half-sawn wall with blocks at the bottom"),
    ("Gezaagde betonblokken op de vloer bij het balkon", "Sawn concrete blocks on the floor by the balcony"),
    ("Ladderlift en container op straat, gezien vanaf de verdieping", "Ladder lift and skip in the street, seen from the flat"),
    ("Portaalstempeling bij dezelfde wand, de stalen ligger ligt klaar", "Propping frame at the same wall, the steel beam ready on the floor"),
    ("Stalen ligger in grondverf boven de nieuwe opening", "Steel beam in primer above the new opening"),
    ("Geplaatste stalen ligger over de brede doorbraak", "Steel beam installed over the wide opening"),
    ("Afgetimmerde ligger tegen het plafond", "Beam boxed in against the ceiling"),
]

CONTACT = [
    ("Weten wat jouw muur kost?", "Want to know what your wall will cost?"),
    ("Stuur je gegevens en een korte omschrijving. Je hoort binnen één werkdag van ons, met een concreet voorstel of de vragen die we nog hebben.",
     "Send your details and a short description. You will hear from us within one working day, with a concrete proposal or the questions we still have. We reply in English."),
    ("<strong>Tip:</strong> stuur alvast een paar foto's mee. De muur zelf, de ruimte erboven en, als je die hebt, een plattegrond. Daarmee kunnen we meteen serieus rekenen.",
     "<strong>Tip:</strong> send a few photos along. The wall itself, the room above it and, if you have one, a floor plan. That lets us start calculating straight away."),
    ('value="Aanvraag via draagmuurkoning.nl"', 'value="Request via draagmuurkoning.nl (English)"'),
    ('value="https://www.draagmuurkoning.nl/bedankt/"', 'value="https://www.draagmuurkoning.nl/en/thank-you/"'),
    (">Naam<", ">Name<"),
    (">Woonplaats<", ">Town or city<"),
    (">Telefoon<", ">Phone<"),
    (">E-mail<", ">Email<"),
    ("Wat wil je laten doorbreken?", "What would you like removed?"),
    ("Bijvoorbeeld: muur tussen keuken en woonkamer, ongeveer 4 meter, jaren-60 rijtjeshuis.",
     "For example: the wall between kitchen and living room, about 4 metres, 1960s terraced house."),
    ("Verstuur aanvraag", "Send request"),
]

HOME = CARROUSEL + CONTACT + [
    ("Draagmuur doorbreken: berekening, vergunning en uitvoering | De Draagmuurkoning",
     "Load-bearing wall removal in the Netherlands, in English | De Draagmuurkoning"),
    ("Draagmuur doorbreken van berekening tot strakke wand. Eén team dat rekent, tekent, de vergunning regelt, het staal zet en afwerkt. Betuwe, Nijmegen en Arnhem.",
     "Load-bearing wall removal handled end to end, in English: structural calculation, drawings, the municipal permit, the steel and the finished wall. Betuwe, Nijmegen and Arnhem."),
    ("Eén team dat rekent, tekent, de vergunning regelt, het staal zet en afwerkt. Eén aanspreekpunt en één planning.",
     "One team for the calculation, the drawings, the permit, the steel and the finishing. One point of contact and one schedule."),
    ("Draagmuur doorbreken · van berekening tot afwerking",
     "Load-bearing wall removal · from calculation to finished wall"),
    ("Die muur kan er <em>gewoon uit.</em>", "That wall <em>can simply go.</em>"),
    ("Eén team dat rekent, tekent, de vergunning regelt, het staal zet en de wand strak oplevert. Eén aanspreekpunt en één planning, van de eerste foto tot de afgewerkte wand.",
     "One team that calculates, draws, arranges the permit, installs the steel and hands the wall back finished. One point of contact and one schedule, from your first photo to the finished wall. Everything in English, including the paperwork with the municipality."),
    ("Wat kost jouw doorbraak?", "What will it cost?"),
    ("Constructeur in het eigen team", "Structural engineer on the team"),
    ("Gestuukt of geverfd opgeleverd", "Handed over plastered or painted"),
    ("Eén aanspreekpunt, begin tot eind", "One contact, start to finish"),
    (">Werkwijze<", ">How it works<"),
    ("Het hele traject, vijf stappen", "The whole job, in five steps"),
    ("De meeste partijen doen één stukje: alleen de berekening, of alleen het zagen. Wij doen het traject van begin tot eind, met eigen mensen.",
     "Most companies do one part: the calculation, or the sawing. We do the whole job from start to finish, with our own people. Useful if you do not speak Dutch, because the municipality is our job, not yours."),
    (">Tekenwerk</h3>", ">Drawings</h3>"),
    ("We tekenen de bestaande en de nieuwe situatie, klaar voor de gemeente.",
     "We draw the existing and the new situation, ready for the municipality."),
    (">Berekening</h3>", ">Calculation</h3>"),
    ("Onze eigen constructeur rekent de doorbraak door volgens de Eurocode.",
     "Our own structural engineer calculates the opening to the Eurocode."),
    (">Vergunning</h3>", ">Permit</h3>"),
    ("Wij dienen de aanvraag in en handelen vragen van de gemeente af.",
     "We submit the application and handle the questions the municipality asks."),
    (">Uitvoering</h3>", ">The work</h3>"),
    ("Stutten, zagen, staal stellen en herstellen. Meestal in een paar dagen.",
     "Propping, sawing, setting the steel and making good. Usually within a few days."),
    (">Afwerking</h3>", ">Finishing</h3>"),
    ("Gestuukt of geverfd. Je ziet niet meer dat er een muur stond.",
     "Plastered or painted. You would never know a wall stood there."),
    ("Wil je zelf de afwerking doen of alleen berekening en uitvoering afnemen? Dat kan ook; we splitsen de offerte dan per onderdeel.",
     "Prefer to do the finishing yourself, or only want the calculation and the work? That is fine; we split the quote by part."),
    ("Van dichte wand tot strakke doorgang", "From solid wall to clean opening"),
    ("Klik op een project en blader door de hele klus: aftekenen, stempelen, zagen, staal stellen en afwerken.",
     "Open a project and scroll through the whole job: marking out, propping, sawing, setting the steel and finishing."),
    ("Bekijk alle projecten", "See all projects"),
    ("Eén team, twee vakmensen", "One team, two trades"),
    ("De kracht van dit team is de combinatie: de constructeur die rekent en de aannemer die uitvoert werken hier onder één naam.",
     "The strength of this team is the combination: the engineer who calculates and the contractor who builds work under one name."),
    ("Uitvoering · MAREE Aanneming", "Execution · MAREE Aanneming"),
    ("Aannemer en specialist in betonzagen en boren. Jordy stut, zaagt, stelt het staal en bouwt af. Sinds 2019 met eigen bedrijf, thuis in de Betuwe.",
     "Contractor and specialist in concrete sawing and drilling. Jordy props, saws, sets the steel and finishes up. Running his own company since 2019, based in the Betuwe."),
    ("Constructie · Cox Constructieadvies", "Structural engineering · Cox Constructieadvies"),
    ("Constructeur, afgestudeerd aan de TU Eindhoven. Simon rekent elke doorbraak door volgens de Eurocode en zet zijn handtekening onder de berekening die naar de gemeente gaat.",
     "Structural engineer, graduated from Eindhoven University of Technology. Simon calculates every opening to the Eurocode and signs the report that goes to the municipality."),
    ("Jordy Maree aan het werk met de zaagmachine", "Jordy Maree at work with the saw"),
    ("Ir. Simon Cox, constructeur", "Ir. Simon Cox, structural engineer"),
    ("Lees ons verhaal", "Read our story"),
    ("Eerst even weten waar je aan toe bent", "Good to know before you start"),
    ("Mag ik zomaar een draagmuur doorbreken?", "Can I just remove a load-bearing wall?"),
    ("Nee. Voor het doorbreken van een dragende muur is vrijwel altijd een omgevingsvergunning nodig, met een constructieberekening die aantoont dat je huis veilig blijft. Wij verzorgen beide, dus je hoeft zelf niets met de gemeente te regelen.",
     "No. Removing a load-bearing wall almost always needs an environmental permit (omgevingsvergunning), together with a structural calculation showing your home stays safe. We arrange both, so you never have to deal with the municipality in Dutch."),
    ("Wat kost een draagmuur doorbreken?", "What does removing a load-bearing wall cost?"),
    ("Dat hangt af van de overspanning en van wat er op de muur draagt. Reken op enkele duizenden euro's voor het complete traject. Het gaat in twee stappen: na je foto's krijg je een richtprijs voor het geheel en een vaste prijs voor tekening en berekening. Zodra de berekening klaar is, weten we welk staal en welke opleggingen nodig zijn, en dan staat de prijs voor de uitvoering vast.",
     "That depends on the span and on what the wall carries. Expect a few thousand euros for the complete job. It works in two steps: after your photos you get an indicative price for the whole job plus a fixed price for the drawing and the calculation. Once the calculation is done we know which steel and which bearings are needed, and the price for the work is fixed."),
    ("Hoe lang duurt het?", "How long does it take?"),
    ("De uitvoering zelf duurt meestal twee tot vijf werkdagen, inclusief herstelwerk. Daarvoor zit de papierwinkel: tekening, berekening en de vergunningsprocedure van de gemeente. Je krijgt vooraf één planning voor het geheel.",
     "The work itself usually takes two to five working days, including making good. Before that comes the paperwork: drawing, calculation and the municipal permit procedure. You get one schedule for the whole thing up front."),
    ("Kan ik ook alleen de berekening of alleen de uitvoering afnemen?", "Can I order only the calculation, or only the work?"),
    ("Ja. Heb je al een aannemer, dan leveren we tekening en berekening. Ligt er al een goedgekeurde berekening, dan voeren we uit. Het totaalpakket is er voor wie er geen omkijken naar wil hebben.",
     "Yes. If you already have a builder, we deliver the drawing and the calculation. If you already have an approved calculation, we do the work. The complete package is for people who would rather not think about it."),
    ("Alle vragen en antwoorden", "All questions and answers"),
]
